
sudo: required
services: 
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .


script:
  - docker run docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  regeon: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-416257109796"
  backet_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY